// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: message.proto

package messagepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_UPLOAD MessageType = 0
	MessageType_SEARCH MessageType = 1
	MessageType_QUERY  MessageType = 2
	MessageType_UPDATE MessageType = 3
	MessageType_DELETE MessageType = 4
	MessageType_ANY    MessageType = 100
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0:   "UPLOAD",
		1:   "SEARCH",
		2:   "QUERY",
		3:   "UPDATE",
		4:   "DELETE",
		100: "ANY",
	}
	MessageType_value = map[string]int32{
		"UPLOAD": 0,
		"SEARCH": 1,
		"QUERY":  2,
		"UPDATE": 3,
		"DELETE": 4,
		"ANY":    100,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_message_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_message_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

type Pair struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pair) Reset() {
	*x = Pair{}
	mi := &file_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pair) ProtoMessage() {}

func (x *Pair) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pair.ProtoReflect.Descriptor instead.
func (*Pair) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

func (x *Pair) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Pair) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tags          []string               `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	Slices        []*Pair                `protobuf:"bytes,2,rep,name=slices,proto3" json:"slices,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Meta          map[string]string      `protobuf:"bytes,4,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Extra         *anypb.Any             `protobuf:"bytes,5,opt,name=extra,proto3" json:"extra,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{1}
}

func (x *Request) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Request) GetSlices() []*Pair {
	if x != nil {
		return x.Slices
	}
	return nil
}

func (x *Request) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Request) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Request) GetExtra() *anypb.Any {
	if x != nil {
		return x.Extra
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Detail        *Request               `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{2}
}

func (x *Response) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Response) GetDetail() *Request {
	if x != nil {
		return x.Detail
	}
	return nil
}

var File_message_proto protoreflect.FileDescriptor

const file_message_proto_rawDesc = "" +
	"\n" +
	"\rmessage.proto\x12\tmessagepb\x1a\x19google/protobuf/any.proto\".\n" +
	"\x04Pair\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\xf1\x01\n" +
	"\aRequest\x12\x12\n" +
	"\x04tags\x18\x01 \x03(\tR\x04tags\x12'\n" +
	"\x06slices\x18\x02 \x03(\v2\x0f.messagepb.PairR\x06slices\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x120\n" +
	"\x04meta\x18\x04 \x03(\v2\x1c.messagepb.Request.MetaEntryR\x04meta\x12*\n" +
	"\x05extra\x18\x05 \x01(\v2\x14.google.protobuf.AnyR\x05extra\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"d\n" +
	"\bResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12*\n" +
	"\x06detail\x18\x03 \x01(\v2\x12.messagepb.RequestR\x06detail*Q\n" +
	"\vMessageType\x12\n" +
	"\n" +
	"\x06UPLOAD\x10\x00\x12\n" +
	"\n" +
	"\x06SEARCH\x10\x01\x12\t\n" +
	"\x05QUERY\x10\x02\x12\n" +
	"\n" +
	"\x06UPDATE\x10\x03\x12\n" +
	"\n" +
	"\x06DELETE\x10\x04\x12\a\n" +
	"\x03ANY\x10d2\xb9\x02\n" +
	"\tVersatile\x121\n" +
	"\x06Upload\x12\x12.messagepb.Request\x1a\x13.messagepb.Response\x121\n" +
	"\x06Search\x12\x12.messagepb.Request\x1a\x13.messagepb.Response\x120\n" +
	"\x05Query\x12\x12.messagepb.Request\x1a\x13.messagepb.Response\x121\n" +
	"\x06Update\x12\x12.messagepb.Request\x1a\x13.messagepb.Response\x121\n" +
	"\x06Delete\x12\x12.messagepb.Request\x1a\x13.messagepb.Response\x12.\n" +
	"\x03Any\x12\x12.messagepb.Request\x1a\x13.messagepb.ResponseB\x0eZ\f./;messagepbb\x06proto3"

var (
	file_message_proto_rawDescOnce sync.Once
	file_message_proto_rawDescData []byte
)

func file_message_proto_rawDescGZIP() []byte {
	file_message_proto_rawDescOnce.Do(func() {
		file_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)))
	})
	return file_message_proto_rawDescData
}

var file_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_message_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_message_proto_goTypes = []any{
	(MessageType)(0),  // 0: messagepb.MessageType
	(*Pair)(nil),      // 1: messagepb.Pair
	(*Request)(nil),   // 2: messagepb.Request
	(*Response)(nil),  // 3: messagepb.Response
	nil,               // 4: messagepb.Request.MetaEntry
	(*anypb.Any)(nil), // 5: google.protobuf.Any
}
var file_message_proto_depIdxs = []int32{
	1,  // 0: messagepb.Request.slices:type_name -> messagepb.Pair
	4,  // 1: messagepb.Request.meta:type_name -> messagepb.Request.MetaEntry
	5,  // 2: messagepb.Request.extra:type_name -> google.protobuf.Any
	2,  // 3: messagepb.Response.detail:type_name -> messagepb.Request
	2,  // 4: messagepb.Versatile.Upload:input_type -> messagepb.Request
	2,  // 5: messagepb.Versatile.Search:input_type -> messagepb.Request
	2,  // 6: messagepb.Versatile.Query:input_type -> messagepb.Request
	2,  // 7: messagepb.Versatile.Update:input_type -> messagepb.Request
	2,  // 8: messagepb.Versatile.Delete:input_type -> messagepb.Request
	2,  // 9: messagepb.Versatile.Any:input_type -> messagepb.Request
	3,  // 10: messagepb.Versatile.Upload:output_type -> messagepb.Response
	3,  // 11: messagepb.Versatile.Search:output_type -> messagepb.Response
	3,  // 12: messagepb.Versatile.Query:output_type -> messagepb.Response
	3,  // 13: messagepb.Versatile.Update:output_type -> messagepb.Response
	3,  // 14: messagepb.Versatile.Delete:output_type -> messagepb.Response
	3,  // 15: messagepb.Versatile.Any:output_type -> messagepb.Response
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_message_proto_init() }
func file_message_proto_init() {
	if File_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_message_proto_goTypes,
		DependencyIndexes: file_message_proto_depIdxs,
		EnumInfos:         file_message_proto_enumTypes,
		MessageInfos:      file_message_proto_msgTypes,
	}.Build()
	File_message_proto = out.File
	file_message_proto_goTypes = nil
	file_message_proto_depIdxs = nil
}
