// Code generated by "stringer -type errCode -linecomment"; DO NOT EDIT.

package errcode

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OK-0]
	_ = x[Canceled-1]
	_ = x[Unknown-2]
	_ = x[InvalidArgument-3]
	_ = x[DeadlineExceeded-4]
	_ = x[NotFound-5]
	_ = x[AlreadyExists-6]
	_ = x[PermissionDenied-7]
	_ = x[ResourceExhausted-8]
	_ = x[FailedPrecondition-9]
	_ = x[Aborted-10]
	_ = x[OutOfRange-11]
	_ = x[Unimplemented-12]
	_ = x[Internal-13]
	_ = x[Unavailable-14]
	_ = x[DataLoss-15]
	_ = x[Unauthenticated-16]
}

const _errCode_name = "OKCANCELLEDUNKNOWNINVALID_ARGUMENTDEADLINE_EXCEEDEDNOT_FOUNDALREADY_EXISTSPERMISSION_DENIEDRESOURCE_EXHAUSTEDFAILED_PRECONDITIONABORTEDOUT_OF_RANGEUNIMPLEMENTEDINTERNALUNAVAILABLEDATA_LOSSUNAUTHENTICATED"

var _errCode_index = [...]uint8{0, 2, 11, 18, 34, 51, 60, 74, 91, 109, 128, 135, 147, 160, 168, 179, 188, 203}

func (i errCode) String() string {
	if i >= errCode(len(_errCode_index)-1) {
		return "errCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _errCode_name[_errCode_index[i]:_errCode_index[i+1]]
}
