// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: message.proto

package messagepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GDKClient is the client API for GDK service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GDKClient interface {
	Call(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error)
}

type gDKClient struct {
	cc grpc.ClientConnInterface
}

func NewGDKClient(cc grpc.ClientConnInterface) GDKClient {
	return &gDKClient{cc}
}

func (c *gDKClient) Call(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/message.GDK/Call", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GDKServer is the server API for GDK service.
// All implementations must embed UnimplementedGDKServer
// for forward compatibility
type GDKServer interface {
	Call(context.Context, *Message) (*Message, error)
	mustEmbedUnimplementedGDKServer()
}

// UnimplementedGDKServer must be embedded to have forward compatible implementations.
type UnimplementedGDKServer struct {
}

func (UnimplementedGDKServer) Call(context.Context, *Message) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Call not implemented")
}
func (UnimplementedGDKServer) mustEmbedUnimplementedGDKServer() {}

// UnsafeGDKServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GDKServer will
// result in compilation errors.
type UnsafeGDKServer interface {
	mustEmbedUnimplementedGDKServer()
}

func RegisterGDKServer(s grpc.ServiceRegistrar, srv GDKServer) {
	s.RegisterService(&GDK_ServiceDesc, srv)
}

func _GDK_Call_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GDKServer).Call(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.GDK/Call",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GDKServer).Call(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

// GDK_ServiceDesc is the grpc.ServiceDesc for GDK service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GDK_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "message.GDK",
	HandlerType: (*GDKServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Call",
			Handler:    _GDK_Call_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "message.proto",
}
